CREATE TABLE IF NOT EXISTS `data` (
`name` VARCHAR(MAX) NULL,
`description` VARCHAR(MAX) NULL,
`image` VARCHAR(MAX) NULL,
`quantity` INT NULL,
`price` VARCHAR(MAX) NULL,
`category_id` INT NULL
);

INSERT INTO data VALUES
('Quần Jean Nam Rách Gối Màu Đen Trơn','Quần Jean được làm từ chất vải jean mềm mịn\, không bai gião\, co giãn nhẹ và rất ít bị nhăn khi gập./Quần Jean có phom dáng ôm cơ thể\, ống côn bó vừa phải\, nhẹ nhàng tôn dáng người mặc./Đường may của Quần Jean rất chắc chắn cùng với chất liệu vải jean co giãn thoải mái cho người sử dụng có thể vận động./Túi quần sâu thoải mái cho người sử dụng có thể để đồ đạc như điện thoại\, chìa khóa\, ví\, .../','https://salt.tikicdn.com/cache/w390/ts/product/62/b0/a0/32baf6f36abf135af1a6e39daee7c81b.jpg',75,'135.800 ₫',1),
('Quần Jean Nam Đen Dáng Ôm Chất Co Giãn JEAN01','Quần Jean được làm từ chất vải jean cotton mềm mịn\, không bai gião\, ít bị nhăn khi gập và rất ít bám bụi./Quần Jean có phom dáng ôm nhẹ cơ thể\, ống côn bó vừa phải\, nhẹ nhàng tôn dáng người mặc./Đường may của Quần Jean rất chắc chắn thoải mái cho người sử dụng có thể vận động./Túi quần sâu vừa phải dễ dàng cho người sử dụng có thể để đồ đạc như điện thoại\, chìa khóa\, ví tiền\,.../','https://salt.tikicdn.com/cache/w390/ts/product/a9/7c/21/1bbd8d7c75ece8b62b227d6bd976c19c.jpg',76,'129.000 ₫',1),
('Quần jean dài nam trơn thời trang - B2000','Quần được may với chất liệu jean dày loại tốt\, đảm bảo độ bền trong hai năm sử dụng./Form quần mới trẻ trung hơn\, trông bạn sẽ luôn tươi khỏe và năng động trong cả ngày dài./Màu vải được nhuộm kỹ đảm bảo KHÔNG RA MÀU khi giặt\, hãy tha hồ mà giặc chung với quần áo khác của bạn mà không sợ lem màu nhé./Chỉ được dùng là loại lớn giúp gia tang độ cứng cáp và tạo điểm nhấn trên từng đường may./Quần được phối  4 túi với 2 túi quần sau lớn tiện lợi cộng với nút gài chắc chắn cho việc chứa ví hoặc giấy tờ/','https://salt.tikicdn.com/cache/w390/ts/product/23/fb/1f/63c03dc475bdfca8dd38aebc2fa60e0a.jpg',25,'129.000 ₫',1),
('Quần Jean Nam TS351','Quần Jeans Nam TS/Vải jean cao cấp\, co giãn nhẹ/Hàng Được sản xuất tại xưởng lành nghề đường may chắt chắn\, màu jean bền màu/','https://salt.tikicdn.com/cache/w390/ts/product/60/90/f4/9aff972f76a562f831efa964e943b461.jpg',32,'136.700 ₫',1),
('Quần Jean Nam Rách Gối Quần Jeans Nam Rách Phong cách Hàn -2606','Quần Jeans Nam TS/Vải jean cao cấp\, co giãn nhẹ/Hàng Được sản xuất tại xưởng lành nghề đường may chắt chắn\, màu jean bền màu/','https://salt.tikicdn.com/cache/w390/ts/product/98/3f/a6/219fccdbeaf4f78e1c8d21724593ae1b.jpg',35,'142.000 ₫',1),
('Quần jean nam ống suông Q61 (Xanh đen )','Sản phẩm được shop đặt may riêng với chất liệu VẢI DÀY bền bỉ./Màu vải được nhộm kỹ đảm bảo KHÔNG RA MÀU khi giặt./From quần suông rất thoải mái khi mặc./Hình ảnh được chụp với sản phẩm thực đang bán\, cam kết giống hình 100%./','https://salt.tikicdn.com/cache/w390/ts/product/f1/e9/8e/af50353fe00f52e5e1e623e7214bed46.jpg',34,'150.000 ₫',1),
('Quần Jean Nam Đen Chất Co Giãn JEAN51 - Jean','Quần Jean được làm từ chất vải jean cotton mềm mịn\, không bai gião\, ít bị nhăn khi gập và rất ít bám bụi./Quần Jean có phom dáng ôm nhẹ cơ thể\, ống côn bó vừa phải\, nhẹ nhàng tôn dáng người mặc./Đường may của Quần Jean rất chắc chắn thoải mái cho người sử dụng có thể vận động./Túi quần sâu vừa phải dễ dàng cho người sử dụng có thể để đồ đạc như điện thoại\, chìa khóa\, ví tiền\,.../','https://salt.tikicdn.com/cache/w390/ts/product/56/21/a7/634da3acfbb79435e1610ec612fe63e0.jpg',98,'131.800 ₫',1),
('Quần jean dài nam - co giãn- vải dày - xám thời trang -B000','Quần được may với chất liệu jean dày loại tốt\, đảm bảo độ bền trong hai năm sử dụng./Form quần mới trẻ trung hơn\, trông bạn sẽ luôn tươi khỏe và năng động trong cả ngày dài./Màu vải được nhuộm kỹ đảm bảo KHÔNG RA MÀU khi giặt\, hãy tha hồ mà giặc chung với quần áo khác của bạn mà không sợ lem màu nhé./Chỉ được dùng là loại lớn giúp gia tang độ cứng cáp và tạo điểm nhấn trên từng đường may./Quần được phối  4 túi với 2 túi quần sau lớn tiện lợi cộng với nút gài chắc chắn cho việc chứa ví hoặc giấy tờ/','https://salt.tikicdn.com/cache/w390/ts/product/82/4f/c5/8e390f7bbaaef0eac5f1c0e7eb58cc01.jpg',41,'136.000 ₫',1),
('Quần Jean Nam 5S (QB5S003XAH) Màu Xanh 3\, Dáng Ôm Trẻ Trung\, Nam Tính','Tên Sản Phẩm: Quần Jean Nam 5S (QB5S003XAH) Màu Xanh 3\, Dáng Ôm Trẻ Trung\, Nam Tính/Thương Hiệu: Thời Trang Nam Cao Cấp 5S/Màu Sắc: Xanh 3/Kiểu Dáng: Slimfit/Thiết Kế: Cúc Dập Logo 5s\, Có Khóa Kéo Kim Loại/Chất Liệu: 98% Cotton\, 2% Spandex/Size: 29 - 30 - 31 - 32 - 33/Sản Xuất: Việt Nam/','https://salt.tikicdn.com/cache/w390/ts/product/cf/fd/9e/f1bb88a466685c22cfa11934dbcd3412.jpg',57,'299.000 ₫',1),
('Quần Bò Nam Trắng Dáng Ôm JEANTRANG02','Quần Bò được làm từ chất vải jean mềm mịn\, không bai gião\, co giãn nhẹ và rất ít bị nhăn khi gập./Quần Bò có phom dáng ôm cơ thể\, ống côn bó vừa phải\, nhẹ nhàng tôn dáng người mặc./Đường may của Quần Bò rất chắc chắn cùng với chất liệu vải jean co giãn thoải mái cho người sử dụng có thể vận động./Túi quần sâu thoải mái cho người sử dụng có thể để đồ đạc như điện thoại\, chìa khóa\, ví\, .../','https://salt.tikicdn.com/cache/w390/ts/product/b0/74/94/1bc99fe44a796017faa9ad01eecd0405.jpg',53,'145.000 ₫',1),
('quần jean nam','Việc Lựa Chọn Kiểu Quần Sẽ Nói Lên Phong Cách Thời Trang Của Ban/Vải jean cao cấp\, co giãn nhẹ/Hàng Được sản xuất tại xưởng lành nghề đường may chắt chắn\, màu jean bền màu/','https://salt.tikicdn.com/cache/w390/ts/product/bb/4f/d7/8a1cebb098815b01bb4fd9884d89f6cb.jpg',44,'153.000 ₫',1),
('Quần Jean Nam 5S (QB5S002XAH) Màu Xanh 2\, Dáng Ôm Trẻ Trung\, Nam Tính','Tên Sản Phẩm: Quần Jean Nam 5S (QB5S002XAH) Màu Xanh 1\, Dáng Ôm Trẻ Trung\, Nam Tính/Thương Hiệu: Thời Trang Nam Cao Cấp 5S/Màu Sắc: Xanh 2/Kiểu Dáng: Slimfit/Thiết Kế: Cúc Dập Logo 5S\, Khóa Kim Loại/Chất Liệu: 98% Cotton\, 2% Spandex/Size: 29 - 30 - 31 - 32 - 33/Sản Xuất: Việt Nam/','https://salt.tikicdn.com/cache/w390/ts/product/62/21/df/267de7682899b1a391bc4bf1e6313538.jpg',27,'299.000 ₫',1),
('Quần Jean Nam Xanh Đậm Hàn Quốc XANHDAM52 - Xanh Đậm','Quần Jean được làm từ chất vải jean mềm mịn\, không bai gião\, co giãn nhẹ và rất ít bị nhăn khi gập./Quần Jean có phom dáng ôm cơ thể\, ống côn bó vừa phải\, nhẹ nhàng tôn dáng người mặc./Đường may của Quần Jean rất chắc chắn cùng với chất liệu vải jean co giãn thoải mái cho người sử dụng có thể vận động./Túi quần sâu thoải mái cho người sử dụng có thể để đồ đạc như điện thoại\, chìa khóa\, ví\, .../','https://salt.tikicdn.com/cache/w390/ts/product/3e/78/f5/67eb957f5b2bde753a70f88b924cfa2a.jpg',73,'134.000 ₫',1),
('Quần Jean Nam Cao Cấp Co Giản Mạnh 5679','quần có màu xanh bạc form chuẩn đẹp kiểu dáng  y hình/chi Tiết wash rách cá tính trẻ trung/đặc biệt độ co giản mạnh nên khách sẽ rất thoải mái khi mặc ạh/','https://salt.tikicdn.com/cache/w390/ts/product/a5/4b/36/a23809bb24861e0b76e9a980a0f49e80.jpg',65,'136.800 ₫',1),
('Quần Jean Nam 5S (QB5S001DEN) Đen 1\, Dáng Ôm Trẻ Trung\, Nam Tính','Tên Sản Phẩm: Quần Jean Nam 5S (QB5S001DEN) Đen 1\, Dáng Ôm Trẻ Trung\, Nam Tính/Thương Hiệu: Thời Trang Nam Cao Cấp 5S/Màu Sắc: Đen 1/Kiểu Dáng: Slimfit/Thiết Kế: Cúc Dập Logo 5s\, Có Khóa Kéo Kim Loại/Chất Liệu: 98% Cotton\, 2% Spandex/Size: 29 - 30 - 31 - 32 - 33/Sản Xuất: Việt Nam/','https://salt.tikicdn.com/cache/w390/ts/product/ef/06/68/05dfefc75829d28ff756036064173a57.jpg',60,'329.000 ₫',1),
('Quần Jean Nam Cao Cấp Co Giản Mạnh M 5 6 7 8','quần có màu xanh bạc dễ phối nhiều loại áo khác nhau/chi Tiết wash xướt nhẹ cá tính trẻ trung/đặc biệt độ co giản mạnh nên khách sẽ rất thoải mái khi mặc ạh/','https://salt.tikicdn.com/cache/w390/ts/product/b3/2e/63/20a24a05b12c50a1b2dbf91bcf98d835.jpg',26,'130.100 ₫',1);